server:
  port: 8083
spring:
    application:
      name: student-service
    datasource:
      url: jdbc:mysql://localhost:3306/university
      username: root
      password: root
    zipkin:
      base-url: http://localhost:9411


address:
  service:
    url: http://localhost:8082

eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      addressService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        automatic-transition-from-open-to-halp-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 5
        allow-health-indicator-to-fail: true
        register-health-indicator: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# CKT-BREAKER STATE - ACTUATOR STATE
# closed - UP
# open - DOWN
# half-open - UNKNOWN
