server:
  port: 8083
spring:
  application:
    name: student-service
  datasource:
    url: jdbc:mysql://localhost:3306/university
    username: root
    password: root

address:
  service:
    url: http://localhost:8082

eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

