server:
    port: 8082
spring:
    application:
        name: address-service
    datasource:
        url: jdbc:mysql://localhost:3306/university
        username: root
        password: root
    zipkin:
        base-url: http://localhost:9411

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka